# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener:
        enabled: true
        default_format: json
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
    view:
        view_response_listener: true
        formats:
            json: true
            xml: true
